spring.application.name=student
spring.datasource.url=jdbc:mysql://localhost:3306/std
spring.datasource.username=root
spring.datasource.password=Heena@0563
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true